### ISSUE TITLE
Skills empty list

### ISSUE THREAD

**Issue by amelinfo** [pbearne/Bullhorn2WP#5]
Hi, i have problem with skills required in the post . Even the custom field skills is null , however , there is kills in the posts . Have you any ideas ? Thanks you

**Comment by amelinfo** [comment]
$skillList = self::get_skill_list();
        foreach($skillList as $key=>$skill){

            $skill_ids[] = $key;
        }
        if ( ! empty( $skill_ids ) ) {
...
}

i added this to attach_skills($,$) function

**Comment by pbearne** [comment]
thanks I have updated the code
